"""
Django settings for https project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@&(!4kpvvb(3rbt(ctqrvz4r(=s+yi9w7f6hnizcmxvld1-u)e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] # <- Ajouter cette ligne pour HTTPS en Développement

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',  # <- Ajouter cette ligne pour HTTPS
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'https.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'https.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Activation du HTTPS (déjà fait si vous utilisez runserver_plus ou un serveur frontal)
# SECURE_SSL_REDIRECT = True  # Redirige HTTP vers HTTPS (désactivez en développement si vous utilisez runserver_plus)
if DEBUG:
    SECURE_SSL_REDIRECT = False  # Redirige HTTP vers HTTPS (désactivez en développement si vous utilisez runserver_plus)

# Commun au Developpement comme en Production
# Sécurité des cookies
SESSION_COOKIE_SECURE = True    # Les cookies de session ne sont envoyés qu'en HTTPS
CSRF_COOKIE_SECURE = True       # Les cookies CSRF ne sont envoyés qu'en HTTPS
SESSION_COOKIE_HTTPONLY = True  # Empêche l'accès aux cookies via JavaScript (protection contre XSS)
CSRF_COOKIE_HTTPONLY = True     # Idem pour les cookies CSRF
SESSION_COOKIE_SAMESITE = 'Lax'  # Protection contre les attaques CSRF (recommandé)
CSRF_COOKIE_SAMESITE = 'Lax'     # Idem pour les cookies CSRF

# Paramètres des sessions
SESSION_COOKIE_AGE = 1209600     # Durée de vie des cookies de session (2 semaines en secondes)
SESSION_SAVE_EVERY_REQUEST = True  # Sauvegarde la session à chaque requête (optionnel)

# En PRODUCTION
# # HSTS (HTTP Strict Transport Security)
# SECURE_HSTS_SECONDS = 31536000  # 1 an
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# En développement, cela suffit
# Backend de session (par défaut : base de données)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Stockage en base de données
# ou (vérifier comment le configurer en production)
# -----------------
# Stockage en cache (plus rapide)
# -----------------

# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': '127.0.0.1:11211',  # Adresse de votre serveur Memcached
#     }
# }
